<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Capture.PNG" />
    <None Remove="myCalci.PNG" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="AssemblyInfo.cs" />
    <Resource Include="myCalci.PNG" />
  </ItemGroup>

</Project>
